# Generated by Django 3.0.7 on 2020-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slot',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
