# Generated by Django 3.0.7 on 2020-06-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_coindispenser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinDispenser',
        ),
    ]
