# Generated by Django 3.0.7 on 2020-06-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_coindispenser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDispenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('added', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
