# Generated by Django 3.0.7 on 2020-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_coindispenser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindispenser',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
