# Generated by Django 3.0.7 on 2020-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_coindispenser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
