# Generated by Django 3.0.7 on 2020-06-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200620_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='amount',
        ),
    ]
